spring:
   application:
      name: s2-movie-info-service
server:
   port: ${PORT:8082}
eureka:
   client:
      fetchRegistry: true
      registryFetchIntervalSeconds: 5
      serviceUrl:
         defaultZone: ${EUREKA_URI:http://ec2-52-14-205-125.us-east-2.compute.amazonaws.com:8761/eureka/}
   instance:
      preferIpAddress: true